apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  labels:
    app: autoscaling-lab
    mode: api
    profile: balanced
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoscaling-lab
  template:
    metadata:
      labels:
        app: autoscaling-lab
        mode: api
        profile: balanced
    spec:
      containers:
        - name: app
          image: nginx:alpine
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo '{"status":"ok"}' > /usr/share/nginx/html/index.html
              nginx -g 'daemon off;'
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
